# Generated by Django 4.1 on 2022-08-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_remove_urllink_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllink',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
