# Generated by Django 4.1 on 2022-08-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_alter_urllink_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllink',
            name='link',
            field=models.CharField(max_length=400),
        ),
    ]
